FROM registry.fedoraproject.org/fedora-toolbox:latest

RUN dnf install -y \
        speech-dispatcher \
        speech-dispatcher-utils \
        kmouth \
        qt6-qtspeech-speechd \
        qt5-qtspeech-speechd \
        python3-pip \
        alsa-utils \
        curl \
        dbus-daemon \
        plasma-breeze-qt6 \
        breeze-icon-theme \
        sudo \
        passwd \
    && dnf clean all

RUN pip3 install --no-cache-dir --break-system-packages piper-tts

RUN mkdir -p /usr/share/piper-voices \
    && curl -L https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_US/amy/medium/en_US-amy-medium.onnx \
        -o /usr/share/piper-voices/en_US-amy-medium.onnx \
    && curl -L https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_US/amy/medium/en_US-amy-medium.onnx.json \
        -o /usr/share/piper-voices/en_US-amy-medium.onnx.json

COPY piper-generic.conf /etc/speech-dispatcher/modules/piper-generic.conf

RUN sed -i 's/^[[:space:]]*AddModule/#AddModule/' /etc/speech-dispatcher/speechd.conf \
    && echo 'AddModule "piper-generic" "sd_generic" "piper-generic.conf"' >> /etc/speech-dispatcher/speechd.conf \
    && sed -i 's/DefaultModule espeak-ng/DefaultModule piper-generic/g' /etc/speech-dispatcher/speechd.conf

RUN mkdir -p /etc/profile.d /etc/fish/conf.d \
    && printf 'export QT_ENABLE_REGEXP_JIT=0\nexport QV4_FORCE_INTERPRETER=1\n' > /etc/profile.d/kmouth-jit.sh \
    && printf 'set -gx QT_ENABLE_REGEXP_JIT 0\nset -gx QV4_FORCE_INTERPRETER 1\n' > /etc/fish/conf.d/kmouth-jit.fish

CMD ["/usr/bin/kmouth"]
